flags: {}
packages:
- '.'
- location:
    git: https://github.com/robstewart57/cal-src.git
    commit: 03d12a3272d1172fa64326bc0198bc0a0bc11b80
- location:
    git: https://github.com/BNFC/bnfc.git
    commit: 6160fe65516fa3af8dde1139c504653d45aba272
  subdirs:
  - source
  extra-dep: true

resolver: lts-8.23

extra-deps:
- alex-3.2.1
- BNFC-2.8