flags: {}
packages:
- '.'
- location:
    git: https://github.com/robstewart57/cal-src.git
    commit: c03f6c8d02fe9f1c771adf60421d786b837fd090
- location:
    git: https://github.com/BNFC/bnfc.git
    commit: 6160fe65516fa3af8dde1139c504653d45aba272
  subdirs:
  - source
  extra-dep: true
 
resolver: lts-7.16

extra-deps:
- alex-3.2.1
- BNFC-2.8