resolver: lts-14.16
packages:
- '.'
extra-deps:
- alex-3.2.5
- BNFC-2.8.3
- git: https://github.com/robstewart57/cal-src.git
  commit: 03d12a3272d1172fa64326bc0198bc0a0bc11b80
- Cabal-2.0.1.1
- containers-0.5.11.0
- binary-0.8.8.0
- text-1.2.4.0
